# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='pagename',
            field=models.CharField(max_length=32),
        ),
    ]
