# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170111_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutme',
            new_name='About',
        ),
    ]
