# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170111_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='Write something about website.'),
        ),
    ]
