# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170111_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highlight',
            field=models.CharField(default='hey', max_length=300),
        ),
    ]
