# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_post_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='highlight',
            field=models.TextField(max_length=300),
        ),
    ]
