# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20170111_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
