# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20170111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
