# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-29 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20170113_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
