# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20170129_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='Write something about yourself. HTML allowed'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='pagename',
            field=models.CharField(max_length=32),
        ),
    ]
