# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20170226_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='pagename',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
