# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='forurl',
        ),
    ]
