# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-29 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highlight',
        ),
    ]
