# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20170221_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='HTML allowed.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagline',
            field=models.CharField(blank=True, default='Write a brief detail or leave empty.', max_length=50),
        ),
    ]
